# ARQUIVO GERADO POR `theme set tokyonight` — NÃO EDITE.

theme[main_bg]=""
theme[main_fg]="#c0caf5"
theme[title]="#9aa5ce"
theme[hi_fg]="#c0caf5"

theme[selected_bg]="#3b4261"
theme[selected_fg]="#e0af68"
theme[inactive_fg]="#292e42"

theme[graph_text]="#7aa2f7"
theme[meter_bg]="#7aa2f7"
theme[proc_misc]="#bb9af7"
theme[div_line]="#565f89"

theme[cpu_box]="#7dcfff"
theme[mem_box]="#9ece6a"
theme[net_box]="#bb9af7"
theme[proc_box]="#7aa2f7"

theme[temp_start]="#7dcfff"
theme[temp_mid]="#e0af68"
theme[temp_end]="#7aa2f7"

theme[cpu_start]="#e0af68"
theme[cpu_mid]="#7dcfff"
theme[cpu_end]="#7aa2f7"

theme[free_start]="#7aa2f7"
theme[free_mid]="#7aa2f7"
theme[free_end]="#7aa2f7"

theme[cached_start]="#bb9af7"
theme[cached_mid]="#bb9af7"
theme[cached_end]="#bb9af7"

theme[available_start]="#9ece6a"
theme[available_mid]="#9ece6a"
theme[available_end]="#9ece6a"

theme[used_start]="#7dcfff"
theme[used_mid]="#7dcfff"
theme[used_end]="#7dcfff"

theme[download_start]="#9ece6a"
theme[download_mid]="#7aa2f7"
theme[download_end]="#7aa2f7"

theme[upload_start]="#7dcfff"
theme[upload_mid]="#7aa2f7"
theme[upload_end]="#7aa2f7"

theme[process_start]="#9ece6a"
theme[process_mid]="#7aa2f7"
theme[process_end]="#7aa2f7"
