# ARQUIVO GERADO POR `theme set tokyonight` — NÃO EDITE.
# Para trocar só o wallpaper, sem trocar de tema: rofi-script wallpaper

splash = false
ipc = true

wallpaper {
    monitor =
    path = @@ASSETS@@/wallpapers/tropical-beach.jpeg
    fit_mode = cover
}
